server:
  port: 80

spring:
  application:
    name: cloud-payment-service


mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: cn.silince.cn.silince.cn.entities    # 所有Entity别名类所在包


